name: Build Docker images

on:
  push:
  #  branches: [ master ]
  workflow_dispatch:
# https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-secrets
# https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  packages: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-18.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.1

      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2.0.0
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.sha }}
            ${{ runner.os }}-buildx-
      # START workaround for --cache-from fails if cache does not already exist
      - name: Docker cache Fix
        run: |
          [[ -f /tmp/.buildx-cache/index.json ]] || echo "FROM alpine" | docker buildx build - --cache-to type=local,dest=/tmp/.buildx-cache,mode=max
      # Temp fix1
      #    https://github.com/docker/buildx/issues/206
#      - name: cache Fix, if cache does not already exist, create Dockerfile.dummy
#        run: echo "FROM alpine" > Dockerfile.dummy
#      - uses: docker/build-push-action@v2
#        with:
#          context: .
#          file: Dockerfile.dummy
#          platforms: |
#            linux/amd64
#          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
#      - name: cache Fix, Move cache
#        run: |
#          set -vx
#          # delete cache dir if index.json not exist
#          #[[ -f /tmp/.buildx-cache/index.json ]] || rm -rf /tmp/.buildx-cache
#          # move dummy docker cache over if index.json not exist
#          [[ -f /tmp/.buildx-cache/index.json ]] || mv /tmp/.buildx-cache-new /tmp/.buildx-cache
#      # END workaround for --cache-from fails if cache does not already exist

      - uses: docker/metadata-action@v3.8.0
        id: meta
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            # minimal
            type=schedule
            # default
            type=schedule,pattern=nightly
            # handlebars
            type=schedule,pattern={{date 'YYYYMMDD'}}
            # semver
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            # dynamically set the branch name as a prefix
            type=sha,prefix={{branch}}-
            
            #type=schedule,pattern=master
            #type=ref,event=branch
            #type=semver,pattern={{version}}
            #type=semver,pattern={{major}}.{{minor}}
            #type=semver,pattern={{major}}
            #  # minimal
            # type=semver,pattern={{version}}
            # use custom value instead of git tag
            # type=semver,pattern={{version}},value=v1.0.0

      - name: Login to GitHub
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.9.0
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }} # importent to catch a rogue like PR
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          #cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
